# Usa a imagem leve do NGINX
FROM nginx:stable-alpine

# Copia arquivos do frontend para o diretório do NGINX
COPY index.html /usr/share/nginx/html/
COPY style.css /usr/share/nginx/html/
COPY script.js /usr/share/nginx/html/

# Copia configuração personalizada do NGINX
COPY default.conf /etc/nginx/conf.d/default.conf

# Expondo porta do frontend
EXPOSE 8080

# Inicia o NGINX
CMD ["nginx", "-g", "daemon off;"]